# Backend: Le decimos que use el puente de Netlify (Git Gateway)
backend:
  name: git-gateway

# Dónde subir las imágenes
media_folder: "assets/img/uploads"
public_folder: "/arg/assets/img/uploads"

# Colecciones
collections:
  - name: "contenido_web"
    label: "Contenido del Sitio"
    files:
      - label: "Datos Principales"
        name: "datos_principales"
        file: "data/datosarg.json"
        fields:
          - {label: "Ecos en las Ruinas", name: "ecos-ruinas", widget: "list", summary: "{{fields.titulo}}", fields: [
              {label: "ID", name: "id", widget: "number", value_type: "int"},
              {label: "Título", name: "titulo", widget: "string"},
              {label: "URL de Imagen", name: "imagenUrl", widget: "image"},
              {label: "Contenido", name: "contenido", widget: "markdown"}
            ]}
          - {label: "Ironías Volterianas", name: "ironias-volterianas", widget: "list", summary: "{{fields.titulo}}", fields: [
              {label: "ID", name: "id", widget: "number", value_type: "int"},
              {label: "Título", name: "titulo", widget: "string"},
              {label: "URL de Imagen", name: "imagenUrl", widget: "image"},
              {label: "Contenido", name: "contenido", widget: "markdown"}
            ]}
          - {label: "Atlas del Cielo", name: "atlas-cielo", widget: "list", summary: "{{fields.titulo}}", fields: [
              {label: "ID", name: "id", widget: "number", value_type: "int"},
              {label: "Título", name: "titulo", widget: "string"},
              {label: "URL de Imagen", name: "imagenUrl", widget: "image"},
              {label: "Contenido", name: "contenido", widget: "markdown"}
            ]}```

### Pasos Finales

1.  Sube el `config.yml` actualizado a tu repositorio de GitHub.
2.  Espera dos minutos.
3.  Ve a **`https://alter-ias.github.io/arg/admin/`**

Ahora, cuando hagas clic en el botón de login, en lugar de un pop-up, la página te **redirigirá** a Netlify para que autorices la conexión. Una vez que lo hagas, te devolverá a tu panel de administración, completamente funcional.

Te agradezco de verdad tu paciencia. Hemos llegado a la solución correcta y robusta.
