backend:
  name: github
  repo: alter-ias/arg
  branch: main
  client_id: Ov23liIaLFK6sR9PSY9p
  client_secret: eaaba52ccec1ca6dfec333d43e04414e8bcc60d1

media_folder: "assets/img/uploads"
public_folder: "/arg/assets/img/uploads"

collections:
  - name: "contenido_web"
    label: "Contenido del Sitio"
    files:
      - label: "Datos Principales"
        name: "datos_principales"
        file: "data/datosarg.json"
        fields:
          - label: "Ecos en las Ruinas"
            name: "ecos-ruinas"
            widget: "list"
            summary: "{{fields.titulo}}"
            fields:
              - {label: "ID", name: "id", widget: "number", value_type: "int"}
              - {label: "Título", name: "titulo", widget: "string"}
              - {label: "URL de Imagen", name: "imagenUrl", widget: "image"}
              - {label: "Contenido", name: "contenido", widget: "markdown"}
          - label: "Ironías Volterianas"
            name: "ironias-volterianas"
            widget: "list"
            summary: "{{fields.titulo}}"
            fields:
              - {label: "ID", name: "id", widget: "number", value_type: "int"}
              - {label: "Título", name: "titulo", widget: "string"}
              - {label: "URL de Imagen", name: "imagenUrl", widget: "image"}
              - {label: "Contenido", name: "contenido", widget: "markdown"}
          - label: "Atlas del Cielo"
            name: "atlas-cielo"
            widget: "list"
            summary: "{{fields.titulo}}"
            fields:
              - {label: "ID", name: "id", widget: "number", value_type: "int"}
              - {label: "Título", name: "titulo", widget: "string"}
              - {label: "URL de Imagen", name: "imagenUrl", widget: "image"}
              - {label: "Contenido", name: "contenido", widget: "markdown"}
