# Backend: Autenticación directa con GitHub (el método más robusto para este caso)
backend:
  name: github
  repo: alter-ias/arg # Tu usuario/repositorio
  branch: main # Tu rama principal
  
  # --- ¡ACCIÓN REQUERIDA! ---
  # Pega aquí el Client ID y el Client Secret de tu aplicación OAuth de GitHub.
  client_id: Ov23liIaLFK6sR9PSY9p
  client_secret: eaaba52ccec1ca6dfec333d43e04414e8bcc60d1

# Dónde subir las imágenes
media_folder: "assets/img/uploads"
public_folder: "/arg/assets/img/uploads"

# Colecciones
collections:
  - name: "contenido_web"
    label: "Contenido del Sitio"
    files:
      - label: "Datos Principales"
        name: "datos_principales"
        file: "data/datosarg.json"
        fields:
          - {label: "Ecos en las Ruinas", name: "ecos-ruinas", widget: "list", summary: "{{fields.titulo}}", fields: [
              {label: "ID", name: "id", widget: "number", value_type: "int"},
              {label: "Título", name: "titulo", widget: "string"},
              {label: "URL de Imagen", name: "imagenUrl", widget: "image"},
              {label: "Contenido", name: "contenido", widget: "markdown"}
            ]}
          # ... (resto de tus colecciones)
