# --- CONFIGURACIÓN DE DIAGNÓSTICO ---

backend:
  name: github
  repo: alter-ias/arg # Tu repositorio: usuario/nombre
  branch: main # Tu rama principal
  auth_type: pkce
  
  # ACCIÓN: Pega tu Client ID aquí. Asegúrate de que no haya espacios extra.
  app_id: Ov23liIaLFK6sR9PSY9p
# El resto de la configuración se omite para la prueba.
# Si esto funciona, añadiremos lo demás.
media_folder: "assets/img/uploads"
public_folder: "/arg/assets/img/uploads"
collections:
  - name: "test_collection"
    label: "Entrada de Prueba"
    folder: "_test"
    create: true
    fields:
      - {label: "Título de Prueba", name: "title", widget: "string"}
