  # Backend: Le decimos que use el servicio de Netlify para la autenticación con GitHub
backend:
  name: github
  repo: alter-ias/arg # Tu usuario/repositorio (esto está bien)
  branch: main # Tu rama principal (esto está bien)
  auth_type: "pkce"
  
  # --- ¡ACCIÓN REQUERIDA! ---
  # Pega aquí tu "Client ID" de la aplicación OAuth de GitHub.
  # Reemplaza TODO lo que está después de "app_id:".
  app_id: Ov23liIaLFK6sR9PSY9p
  
# Dónde subir las imágenes
media_folder: "assets/img/uploads"
public_folder: "/arg/assets/img/uploads"

# Colecciones: Editaremos un solo archivo
collections:
  - name: "contenido_web"
    label: "Contenido del Sitio"
    files:
      - label: "Datos Principales"
        name: "datos_principales"
        file: "data/datosarg.json"
        fields:
          - label: "Ecos en las Ruinas"
            name: "ecos-ruinas"
            widget: "list"
            summary: "{{fields.titulo}}"
            fields:
              - {label: "ID", name: "id", widget: "number", value_type: "int"}
              - {label: "Título", name: "titulo", widget: "string"}
              - {label: "URL de Imagen", name: "imagenUrl", widget: "image"}
              - {label: "Contenido", name: "contenido", widget: "markdown"}
          - label: "Ironías Volterianas"
            name: "ironias-volterianas"
            widget: "list"
            summary: "{{fields.titulo}}"
            fields:
              - {label: "ID", name: "id", widget: "number", value_type: "int"}
              - {label: "Título", name: "titulo", widget: "string"}
              - {label: "URL de Imagen", name: "imagenUrl", widget: "image"}
              - {label: "Contenido", name: "contenido", widget: "markdown"}
          - label: "Atlas del Cielo"
            name: "atlas-cielo"
            widget: "list"
            summary: "{{fields.titulo}}"
            fields:
              - {label: "ID", name: "id", widget: "number", value_type: "int"}
              - {label: "Título", name: "titulo", widget: "string"}
              - {label: "URL de Imagen", name: "imagenUrl", widget: "image"}
              - {label: "Contenido", name: "contenido", widget: "markdown"}
